version: "3"
tasks:
  build: 
    cmds:
      - (cd local && terraform apply -var-file="local.tfvars" --auto-approve)
  destroy: 
    cmds:
      - (cd local && terraform destroy -var-file="local.tfvars" --auto-approve)
  plan: 
    cmds:
      - (cd local && terraform plan -var-file="local.tfvars")
  init:
    cmds:
      - (cd local && terraform init)
