version: "3"
tasks:
  build: 
    cmds:
      - (cd local && terraform apply -var-file="local.tfvars" --auto-approve)
  destroy: 
    cmds:
      - (cd local && terraform destroy -var-file="local.tfvars" --auto-approve)
  plan: 
    cmds:
      - (cd local && terraform plan -var-file="local.tfvars")
  init:
    cmds:
      - (cd local && terraform init)
  codespace_k8s_setup:
    cmds:
      - minikube start
      - minikube tunnel
  codespsace_portforward:
    cmds:
      - kubectl port-forward --namespace ingress-nginx service/nginx-ingress 8080:80
